-- CreateTable
CREATE TABLE "Note" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "wordId" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Note_wordId_fkey" FOREIGN KEY ("wordId") REFERENCES "Toeiclist" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
